server:
  port: 9003
  servlet:
    context-path: /
    
spring:
  datasource:
    url: jdbc:mysql://rm-wz936477ppnwe9zamfo.mysql.rds.aliyuncs.com:3306/shiro-web?characterEncoding=utf-8
    username: syp_test
    password: a123456!


shiro:
  redis:
    host: r-uf6tknbhr9hzsfyzukpd.redis.rds.aliyuncs.com
    port: 6379
    timeout: 6000
    password: LaiTest@2020

    
  
logBaseUrl: http://192.168.11.241:9002/log






