
spring:
  profiles:
    active: dev
  
  mvc:
    view:
      prefix: /html

mybatis:
  mapper-locations: classpath:com/yucong/mapper/*.xml
  # 数据库下划线转驼峰标识
  configuration:
    map-underscore-to-camel-case: true


pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: false
  support-methods-arguments: true
  
    
password:
  algorithmName: md5
  hashIterations: 2
  


###################  beetl配置  ###################
beetl:
  #delimiter-statement-start: @   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false




